services:
  - type: web
    name: diancan-backend
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
